name: Manual Web Build & Release

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust if needed

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Make sure this outputs your build folder

      - name: Verify Build Folder
        run: ls -la dist  # Change 'dist' if your build folder is different

      - name: Zip Build Folder
        run: zip -r web-build.zip dist  # Replace 'dist' if needed

      - name: Create or Update Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          tag: manual-${{ github.run_number }}
          name: Web Build #${{ github.run_number }}
          files: web-build.zip
          overwrite: true  # Overwrites previous release with same tag if exists
